export const PALE_TITLES_SIZE = 11

export const MAJOR_BUILDINGS_POLYGONS_MINZOOM = 13.7
export const MINOR_ROADS_MINZOOM = MAJOR_BUILDINGS_POLYGONS_MINZOOM

export const DEAD_BUILDINGS_CIRCLES_MINZOOM = 12.5

export const CITY_BULK_FULL_OPACITY_MAXZOOM = 11.5

export const NON_SELECTABLE_TITLE_OPACITY = 0.55

export const AREA_TYPES = {
    INSTITUTION: 'institution',
    CEMETERY: 'cemetery',
    SQUARE: 'square',
    TOWN: 'town',
    AIRPORT: 'airport',
    BRIDGE: 'bridge'
}

export const MINIMAL_ZOOM_ON_BUILDING_SELECT = 15.2

export const SECONDARY_BLDGS_MINZOOM = 13.3

export const SECONDARY_TITLES_MINZOOM = 15

export const BORING_BLDGS_POLYGONS_MINZOOM = 15

export const CURSOR_POINTER_MINZOOM = 14.5