export const DR_IM = {
    TITLES: 0,
    PIN: 0,

    DEAD_BUILDINGS_FILL: 1,
    SELECTED_POLYGON: 1,

    CITY_WALLS: 2,
    HISTORIC_CIRCLES: 2,
    SELECTABLE_BORDER: 2,
    HISTORIC_POLYGONS: 2,

    BORING_CIRCLES: 2.1, // slightly below historic circles

    DEAD_BUILDINGS_CIRCLES: 3,
    MAJOR_ROADS_THIN: 3,
    IMPORTANT_BORING_BLDG_FILL: 3,

    MAJOR_ROADS_THICK: 4,
    ROADS: 4,
    CABLE_CAR_LINE: 4,

    BRIDGE_AREAS: 5,
    RAILWAY_LINE: 5,
    BORING_BLDG_FILL: 5,

    WATER_AREAS_FILL: 6,
    RIVER_LINES: 6.05,

    CITY_BULK: 6.1,

    LAND_AREAS: 6.2,

    TOWNS_FILL: 7,

    ISLAND_FILL: 9,

    SEA_FILL: 10

}
